### ISSUE TITLE
Add a fallback method if there are no matching hears methods

### ISSUE THREAD

**Issue by robmorgan** [BeepBoopHQ/witbot#1]
Hi,

Great job on the library, I've been using it to write a few bots.

One thing I'd like to add though is the ability to specify a fallback/catch all method.

Often I'd like to reply with:

_Sorry, I do not understand_ etc

Looking through the source, its not currently possibly right? or is there a smarter way to do it?

**Comment by mbrevoort** [comment]
Great point. No I don't think there's good way to do this currently. 

Maybe something like this if no known intents are matched: `witbot.otherwise(function(){})`

**Comment by robmorgan** [comment]
@mbrevoort exactly!

**Comment by mbrevoort** [comment]
@robmorgan I just added `otherwise` and published version 1.1.0. Thanks!

**Comment by robmorgan** [comment]
@mbrevoort awesome, I'll try it out tomorrow!
